#!/bin/bash

#SBATCH --job-name=FastQC_trimmed
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=16G
#SBATCH --time=04:00:00
#SBATCH --mail-user=*email*
#SBATCH --mail-type=ALL

module load anaconda3/2023.09-0
conda activate QC_env 

INPUT_DIR=$input_directory_path
OUTPUT_DIR=$output_directory_path

mkdir -p $OUTPUT_DIR

fastqc -t 4 -o $OUTPUT_DIR $INPUT_DIR/*.fastq.gz
