#!/bin/bash 

#SBATCH --job-name=featureCounts
#SBATCH --output=featureCounts_%j.out
#SBATCH --error=featureCounts_%j.err
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=32G
#SBATCH --time=04:00:00
#SBATCH --mail-user=*email*
#SBATCH --mail-type=ALL

BAM_DIR=$BAMfiles_directory_path #should be STAR output directory 
GTF_FILE=$genome_gtf_file_path
OUTPUT_DIR=$output_directory_path

BAM_FILES=$(ls "$BAM_DIR"/*Aligned.sortedByCoord.out.bam)

module load anaconda3/2023.09-0 
conda activate subread_env

featureCounts -a "$GTF_FILE" \
              -t exon \
              -g gene_id \
              -p \
              -s 0 \
              -T 4 \
              -o "${OUTPUT_DIR}/featurecounts_matrix.txt" \
              $BAM_FILES

echo "FeatureCounts complete"
