#!/bin/bash 

INPUT_DIR=”$1”
OUT_DIR=”$2”

#output
mkdir -p “$OUTPUT_DIR”

#load module and environment 
module load anaconda3/2023/09.0 
conda activate multiqc 

#run multiqc 
multiqc “$INPUT_DIR” -o “OUTPUT_DIR”

echo “MultiQC complete” 
