#!/bin/bash

#SBATCH --job-name=MultiQC_trimmed
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --time=01:00:00
#SBATCH --mail-user=*email*
#SBATCH --mail-type=ALL

module load anaconda3/2023.09-0
conda activate QC_env 

INPUT_DIR=$input_directory_path
OUTPUT_DIR=$output_directory_path

mkdir -p $OUTPUT_DIR

multiqc $INPUT_DIR -o $OUTPUT_DIR
