#!/bin/bash

#-------------------------------------------------------------------------------
# description: 
# this script runs MultiQC to summarize quality control reports from a 
# specified input directory. 

# inputs: 
# a directory with QC output files (from FastQC for example)

# outputs: 
# a MultiQC HTML report in the specified output directory 

# be sure to edit INPUT_DIR and OUTPUT_DIR paths with specific paths
#-------------------------------------------------------------------------------

#SBATCH --job-name=MultiQC_trimmed
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --time=01:00:00
#SBATCH --mail-user=*email*
#SBATCH --mail-type=ALL

module load anaconda3/2023.09-0
conda activate QC_env 

INPUT_DIR=$input_directory_path
OUTPUT_DIR=$output_directory_path

mkdir -p $OUTPUT_DIR

multiqc $INPUT_DIR -o $OUTPUT_DIR
