#!/bin/bash 

BASENAME=$1
INPUT_DIR=$2
OUTPUT_DIR=$3
GENOME_DIR=$4

#input
R1=${INPUT_DIR}/${BASENAME}R1_paired.fastq.gz
R2=${INPUT_DIR}/${BASENAME}R2_paired.fastq.gz

#output
mkdir -p $OUTPUT_DIR 
OUTPUT_PREFIX=${OUTPUT_DIR}/${BASENAME}_ 

#run STAR aligner
STAR --runThreadN 12 \
     --runMode alignReads \
     --genomeDir "$GENOME_DIR" \
     --readFilesIn "$R1" "$R2" \
     --readFilesCommand zcat \
     --outFileNamePrefix "$OUTPUT_PREFIX" \
     --outSAMtype BAM SortedByCoordinate \
     --outSAMunmapped Within \
     --outFilterMultimapNmax 20 \
     --alignSJoverhangMin 8 \
     --alignSJDBoverhangMin 3 \
     --outFilterMismatchNmax 999 \
     --outFilterMismatchNoverReadLmax 0.04 \
     --alignIntronMin 20 \
     --alignIntronMax 1000000 \
     --alignMatesGapMax 1000000

echo "STAR alignment completed for $BASENAME"
